### ISSUE TITLE
Request for maintainership

### ISSUE THREAD

**Issue by ocharles** [Holmusk/servant-hmac-auth#44]
As @CircuitHub use this in production, we're interested in keeping it current - and we'd love to help! Could I request maintainer access? I just plan to keep things building, not much more than that for now.

Pinging @arbus.

**Comment by kahlil29** [comment]
Hey @ocharles 👋🏻 
Thanks for raising this and for helping us keep the repo up-to-date! 😄 
I'll be assisting from Holmusk's end. I'll start by helping you get #43 merged 👍🏻

**Comment by ocharles** [comment]
Hi @kahlil29, thanks! Let me know if you need anything :smiley:

**Comment by ocharles** [comment]
Closing as it @kahlil29 is doing a great job maintaining this!

**Comment by kahlil29** [comment]
@ocharles Thanks for the kind words 😸  
I know things haven't progressed very quickly but do highlight or tag me in any issue/PR that needs to be fast-tracked and I'll try my best to prioritize it 🚀
